language: node_js
node_js:
  - 10
env: ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true YARN_GPG=no CC=clang CXX=clang++ npm_config_clang=1
osx_image: xcode8.3 
jobs:
  fast_finish: true
  include:
    - os: windows
      compiler: clang
    - os: osx
      before_install: 
        - brew install git-lfs
        - brew install libgcrypt
    - os: linux
      before_install: sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
      env: ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true YARN_GPG=no
      compiler: clang
cache:
  - npm
  - yarn
  - directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
install:
  - npm install -g xvfb-maybe
  - yarn install
script:
  - yarn run build 
branches:
  only:
    - vue
